function plotHists(floating, diving, flying, timestamps)
    % PLOTHISTS: Plots three histograms, the fist one for floating, the second for
    % flying, the third for diving.
    % 
    % INPUT: three arrays with values for how much a histogram fits to a point
    %
    % OUTPUT: Plot with floating (red), flying (green) and diving (blue).

    plot(timestamps, floating, '-s', ...
                'LineWidth',1, ...
                'color','r', ...
                'MarkerSize',4); 
    hold on;
    plot(timestamps, flying, '-s', ...
                'LineWidth',1, ...
                'color','g', ...
                'MarkerSize',4); 

    plot(timestamps, diving, '-s', ...
                'LineWidth',1, ...
                'color','b', ...
                'MarkerSize',4); 
    title('Histograms');
