function plotAcc(Accel, timeStamp)
    % PLOTACC plots the accellerometer data of a certain time stamp
    % Plots the x-axis red, y-axis green, z-axis blue
    Accel = Accel(find(Accel(:, 2) ==  timeStamp), :);
    plot(Accel(:, 3), Accel(:, 4), '-s','LineWidth',1, ...
                'MarkerEdgeColor','r', ...
                'MarkerFaceColor','auto', ...
                'MarkerSize',4); 
    hold on
    plot(Accel(:, 3), Accel(:, 5), '-s','LineWidth',1, ...
                'MarkerEdgeColor','g', ...
                'MarkerFaceColor','auto', ...
                'MarkerSize',4); 
    plot(Accel(:, 3), Accel(:, 6), '-s','LineWidth',1, ...
                'MarkerEdgeColor','b', ...
                'MarkerFaceColor','auto', ...
                'MarkerSize',4); 
    xlabel('time(1/20 seconds)');
    ylabel('force (mV)');
